### ISSUE TITLE
Rename project - possible copyright violations

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#12]
OpenAI is beginning to enforce their trademark on GPT.
https://techstartups.com/2023/05/04/openai-send-cease-owner-of-sitegpt-ai-forced-to-rebrand/
They may disallow api for any site or project using that name

**Comment by c0sogi** [comment]
My opinion is too. First of all, I changed the project name, and then I will gradually shorten the term chatgpt.

**Comment by c0sogi** [comment]
14812d986574fcd9d0259f1a75d7a32999b24527
