### ISSUE TITLE
Restrict embed to elevated role

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#14]
Possible abuse of shared memory if all authenticated user can embed text. Restrict embedding to admin/editor roles

**Comment by c0sogi** [comment]
Let's consider assigning a vector index to an individual in the next commit

**Comment by Torhamilton** [comment]
Yes good idea, mutes the need for in-browser db. However admin needs to be able to deploy app-wide embeddings available to all users. I opened another issue for admin UI

**Comment by c0sogi** [comment]
58c507453d63571071d33285b66a9bbb3667ebe2

**Comment by Torhamilton** [comment]
This is use case dependent. Maybe a switch to enable/disable for users. Some folks are just going to upload a catalog of books, I can see that happening. Also admin can't guarantee copyrighted works are not being embedded.
