### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#15]
Integrate [FastAPI Admin](https://github.com/fastapi-admin/fastapi-admin) or [Amis version](https://github.com/amisadmin/fastapi-amis-admin)

**Comment by c0sogi** [comment]
Ok i will

**Comment by c0sogi** [comment]
58c507453d63571071d33285b66a9bbb3667ebe2

Go to `/admin` and login with mysql user id & pw
