### ISSUE TITLE
Replace Redis

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#17]
Lets implement [qdrant](https://github.com/qdrant/qdrant) for embeddings. Use Redis for what it's good at - caching chats. Qdrant is fast and stable and excellent at search and filtering see [benchmark](https://qdrant.tech/benchmarks/).
Redis single thread execution is bad for vertical scaling. Down the road we should allow BYOD (bring your own db)

Please implement as separate docker for  independent scaling `docker run -p 6333:6333 qdrant/qdrant`

**Comment by c0sogi** [comment]
Since many of my projects already rely on redis, replacing the database is a very difficult task. Modify that code and request a pull request.

What's more, REDIS is not a CPU-bound operation, so it can handle 100,000+ requests per second quickly, even if it's single-threaded.

**Comment by Torhamilton** [comment]
I am looking into qdrant and will make a pr once I make progress. This stuff is not for Redis - we need capabilities to insert, delete, filter, advance operations with indices etc. We want to offload this task and reduce memory requirements

**Comment by Torhamilton** [comment]
I will close this for now until need is critical.
