### ISSUE TITLE
Display token/word count and cost

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#18]
This will help contain cost.
![Screenshot 2023-05-19 125701](https://github.com/c0sogi/LLMChat/assets/124926616/fb43d2b1-d7fb-4e60-b30f-238a4a549ea8)

Courtesy of  [chatpad](https://github.com/deiucanta/chatpad)

**Comment by c0sogi** [comment]
I'm going to set it to show the number of tokens only. It's too complicated to calculate the cost.

**Comment by Torhamilton** [comment]
Sure closing this for now
