### ISSUE TITLE
text-embedding-ada-002 for embeddings

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#20]
[openai](https://platform.openai.com/docs/guides/embeddings/what-are-embeddings) says to use "text-embedding-ada-002" for all text embeddings. It's very cheap. gpt3.5/4 are 1000x more expensive ` tokenizer_model: str = "text-embedding-ada-002"`

**Comment by c0sogi** [comment]
no. We always use the `text-embedding-ada-002` model for embedding. See the OpenAIEembeddings class. You can see that `model: str = "text-embedding-ada-002"`.

```python
        embeddings: Embeddings = OpenAIEmbeddings(
            client=openai.Embedding,
            openai_api_key=openai_api_key,
        )
```

**Comment by Torhamilton** [comment]
Okay. Don't want to use ada-002 as tokenizer?
