### ISSUE TITLE
Integrate gptCache

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#23]
Lets save some $$$ by implementing [GPTcache](https://github.com/zilliztech/GPTCache)
There is a docker image and I think it may already work with Redis
`$ docker pull zilliz/gptcache:latest
$ docker run -p 8000:8000 -it zilliz/gptcache:latest`

Admin can use temperature settings to bypass cache.

Important: cache must maintain user privacy. Admin can add sitewide cache. This will make FAQ generation a breeze and cost nothing to retrieve cached info each time.

**Comment by c0sogi** [comment]
Unfortunately, this library does not support redis. Instead, you need to use mysql as a cache, and it only supports 'milvus', 'faiss', 'chromadb', and 'hnswlib' as vector databases.

**Comment by Torhamilton** [comment]
Thanks, that was real fast! There is already an open issue for Redis integration https://github.com/zilliztech/GPTCache/issues/271
Let's hope our bet on Redis pays off! I will watch GPTCache
