### ISSUE TITLE
Save embeddings metadata to MySQL

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#24]
Admin should be able to examine and delete redundant vectors by means of stored metadata. Date of inserts, author , title etc should be saved in mysql. Saving in Redis may pollute the vector?

**Comment by c0sogi** [comment]
No It's not a problem to store metadata in Redis, but the problem is that you can't see the data in the admin console. Consider storing your metadata in mysql?

**Comment by Torhamilton** [comment]
Then lets save in mysql, this is critical feature
