### ISSUE TITLE
Make qdrant collection name a constant 

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#33]
`QDRANT_COLLECTION: str = environ["QDRANT_COLLECTION"]`
and 
` shared_vectorestore_name: str = QDRANT_COLLECTION`
This makes an instance of qdrant shareable

**Comment by c0sogi** [comment]
I'll add to the env to set the name of the shared collection.

**Comment by Torhamilton** [comment]
thanks
