### ISSUE TITLE
Message prefix/suffix

### ISSUE THREAD

**Issue by Torhamilton** [c0sogi/LLMChat#35]
Ability to add prefix/suffix instruction to first message in chat. Best as .env variable. I want to instruct openAI about policies. Kindly give me a pointer so I  can attempt this.

**Comment by Torhamilton** [comment]
I added default message for system-role, but I think prefix/suffix would make my task easier

**Comment by c0sogi** [comment]
You can add prefixes and suffixes directly in llms.py, but you can also add GLOBAL_PREFIX, GLOBAL_SUFFIX to your .env. Setting the GLOBAL value will override the prefix and suffix set in LLM. 

f67896718580c460514a80aa23f74cb60df5af49
